export const serviceEnvNames = [
  'API_GATEWAY',
  'AUTH_SVC_ORIGIN',
  'STORAGE_SVC_ORIGIN',
  'COMMUNITY_SVC_ORIGIN',
  'LIBRARY_SVC_ORIGIN',
  'SUBSCRIPTIONS_SVC_ORIGIN',
  'USERS_SVC_ORIGIN',
  'VIDEO_MANAGER_SVC_ORIGIN',
  'VIDEO_STORE_SVC_ORIGIN',
  'VIDEO_PROCESSOR_SVC_ORIGIN',
  'HISTORY_SVC_ORIGIN',
  'SEARCH_SVC_ORIGIN',
];
